# Generated by Django 5.2.15 on 2026-06-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.CharField(max_length=50, verbose_name='Номер столика'),
        ),
    ]
