# Generated by Django 5.2.15 on 2026-06-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_order_customer_phone_alter_order_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('waiter', 'Вызов официанта'), ('bill', 'Просьба счёт')], max_length=20, verbose_name='Тип')),
                ('table_number', models.CharField(max_length=50, verbose_name='Номер столика')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Сервисный вызов',
                'verbose_name_plural': 'Сервисные вызовы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Хит продаж'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_spicy',
            field=models.BooleanField(default=False, verbose_name='Острое'),
        ),
    ]
